title: "Franz Maximilian Buchmann, PhD"
description: "Professional profile – Data Science, Economics & AI"
url: "https://framabu.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast"

# Author information
author:
  name: "Franz Maximilian Buchmann, PhD"
  avatar: "/assets/images/fmb.jpg"
  bio: "Data Scientist experienced in AI, Finance, and Statistics. Passionate about digital and green transformations."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:franz.buchmann07@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/franz-buchmann/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/FraMaBu"

plugins:
  - jekyll-include-cache

# Collections configuration for portfolio
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults for portfolio items
defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      read_time: true