title: "Franz Maximilian Buchmann, PhD"
description: "Professional profile, portfolio, and CV – Data Science, Economics & AI"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast"

author:
  name: "Franz Maximilian Buchmann, PhD"
  email: "franz.buchmann07@gmail.com"
  avatar: "/assets/images/fmb.jpg"

url: "https://framabu.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

paginate: 5
paginate_path: "/blog/page:num/"

header:
  nav:
    - title: "Home"
      url: "/"
    - title: "Portfolio"
      url: "/portfolio/"
    - title: "CV"
      url: "/cv/"
    - title: "Blog"
      url: "/blog/"

collections:
  projects:
    output: true
    permalink: /projects/:title/